### ISSUE TITLE
Bug with graph method

### ISSUE THREAD

**Issue by vfdev-5** [lanpa/tensorboard-pytorch#140]
Hi,

There is an error that arise with the following code:
```python
import torch
from pretrainedmodels.models.inceptionresnetv2 import inceptionresnetv2
from tensorboardX.graph import graph

model1 = inceptionresnetv2(pretrained=False)
x = torch.rand(4, 3, 320, 320)
graph_def1 = graph(model1, x)
```
and the output is 
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-028919b16748> in <module>()
      1 x = torch.rand(4, 3, 320, 320)
----> 2 graph_def1 = graph(model1, x)

/usr/local/lib/python3.5/dist-packages/tensorboardX/graph.py in graph(model, args, verbose)
     90     if verbose:
     91         print(graph)
---> 92     list_of_nodes = parse(graph)
     93     nodes = []
     94     for node in list_of_nodes:

/usr/local/lib/python3.5/dist-packages/tensorboardX/graph.py in parse(graph)
     33 
     34     for n in graph.nodes():
---> 35         attrs = {k: n[k] for k in n.attributeNames()}
     36         attrs = str(attrs).replace("'", ' ')  # singlequote will be escaped by tensorboard
     37         inputs = [i.uniqueName() for i in n.inputs()]

/usr/local/lib/python3.5/dist-packages/tensorboardX/graph.py in <dictcomp>(.0)
     33 
     34     for n in graph.nodes():
---> 35         attrs = {k: n[k] for k in n.attributeNames()}
     36         attrs = str(attrs).replace("'", ' ')  # singlequote will be escaped by tensorboard
     37         inputs = [i.uniqueName() for i in n.inputs()]

/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py in _node_getitem(self, k)
    442     """
    443     sel = self.kindOf(k)
--> 444     return getattr(self, sel)(k)
    445 
    446 

RuntimeError: VariableType::ID() not implemented
```

Actually, the problem is with "constant" nodes. In InceptionResNetV2 in the Block35 in forward method features are multiplied by a scale. And this operation raises above problem. For example, minimal code to reproduce the error:
```python
import torch.nn as nn

class FaultyModel(nn.Module):
    
    def __init__(self):
        super(FaultyModel, self).__init__()
        self.fc = nn.Linear(100, 10)
        
    def forward(self, x):
        x = self.fc(x)
        return x * 0.5

x = torch.rand(4, 100)
model1 = FaultyModel()

# Following is the code of `graph` method
import torch
with torch.onnx.set_training(model1, False):
    try:
        trace, _ = torch.jit.get_trace_graph(model1, x)
    except RuntimeError:
        print("Error occurs, checking if it's onnx problem...")
        try:
            torch.onnx.export(model, args, "/tmp/dummy.pb", verbose=True)
        except RuntimeError:
            print("Your model fails onnx too, please report to onnx team")
        print('No graph saved')        
torch.onnx._optimize_trace(trace, False)
graph_ = trace.graph()

attrs = []
for n in graph_.nodes():
    print(n)
    # attrs = {k: n[k] for k in n.attributeNames()}
    attrs.append({k: [n.kindOf(k), getattr(n, n.kindOf(k))(k)] for k in n.attributeNames()})
```

I don't yet know if this is `pytorch` problem or can be fixed here. Anyway, it could be good to investigate.

PS. Thanks for awesome project !

**Comment by lanpa** [comment]
correct diagnosis.  But it was fixed in #139 lol.

**Comment by vfdev-5** [comment]
@lanpa thanks, sorry for bothering :)

**Comment by lanpa** [comment]
@brijraj08 What's the error message?

**Comment by iandanforth** [comment]
OS: OSX 10.13.2
Python: 3.6.4
Pytorch: 0.4.0
pytorch-tensorboard: installed via

```
pip install git+https://github.com/lanpa/tensorboard-pytorch
```

I'm also still seeing an error

running an unmodified [demo_graph.py](https://github.com/lanpa/tensorboard-pytorch/blob/master/demo_graph.py)

```
/Users/iandanforth/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchvision/models/densenet.py:212: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
/Users/iandanforth/.pyenv/versions/3.6.4/lib/python3.6/site-packages/tensorboardX/graph.py:41: UserWarning: Error getting attributes of node %1 : Dynamic = onnx::Constant[value={2}](), scope: SimpleModel, error is VariableType::ID() not implemented
  warnings.warn("Error getting attributes of node {}, error is {}".format(attrs, e))
Error occurs, No graph saved
```

**Comment by lanpa** [comment]
@iandanforth Does that come from https://github.com/lanpa/tensorboard-pytorch/blob/8d5c9bc5c89aaead92d6be4df6f3c5bb4116b310/demo_graph.py#L133-L136

**Comment by twkillian** [comment]
I've been experiencing the same error, I've commented out the lines @lanpa highlighted and the same error is thrown...
